import { exposureAllowsEvaluation, type GuidanceExposureDecision } from './exposure-decision';
export type PlatformGuidancePosition = 'front' | 'middle' | 'back';
export interface PlatformGuidanceRecord {
  readonly coverageRowId:string; readonly immutableVersion:string; readonly supersededVersion:string; readonly complex:string; readonly constituent:string; readonly priorityCategory:string; readonly categoryEvidence:string; readonly route:string; readonly servicePattern:string; readonly direction:string; readonly destination:string; readonly platformId:string; readonly layoutOrientation:string; readonly frontRearOrder:string; readonly zoneGeometry:string; readonly objectiveType:string; readonly objectiveTarget:string; readonly physicalRelationships:string; readonly zoneBenefit:string; readonly certaintyCeiling:string; readonly accessiblePathVersion:string; readonly restrictions:string; readonly supportedScope:string; readonly unsupportedScope:string; readonly task7RecordVersion:string; readonly durableFieldEvidence:string; readonly verificationDate:string; readonly verifier:string; readonly reverificationTriggers:string; readonly reverificationStatus:string; readonly feedbackCorrections:string; readonly productDecision:string; readonly accessibilityDecision:string; readonly dataQualityDecision:string; readonly contentDecision:string; readonly operationsDecision:string; readonly disposition:string; readonly releasePackage:{ readonly packageVersion:string; readonly inclusion:'included'|'excluded'; readonly scope:string; readonly reason:string; readonly downstreamDecision:'pending'|'approved' }; readonly position:PlatformGuidancePosition; readonly provenance:{ readonly sourceId:string; readonly version:string; readonly immutable:boolean; readonly reviewed:boolean };
}
export interface PlatformGuidanceRequest { readonly complex:string; readonly constituent:string; readonly route:string; readonly servicePattern:string; readonly direction:string; readonly destination:string; readonly platformId:string; readonly orientation:string; readonly objectiveType:string; readonly objectiveTarget:string; readonly accessiblePathVersion:string; readonly now:Date; readonly platformState:'confirmed'|'expected'|'check-signs'; readonly rerouted:boolean; readonly exposure:GuidanceExposureDecision }
const FIELDS = ['coverageRowId','immutableVersion','supersededVersion','complex','constituent','priorityCategory','categoryEvidence','route','servicePattern','direction','destination','platformId','layoutOrientation','frontRearOrder','zoneGeometry','objectiveType','objectiveTarget','physicalRelationships','zoneBenefit','certaintyCeiling','accessiblePathVersion','restrictions','supportedScope','unsupportedScope','task7RecordVersion','durableFieldEvidence','verificationDate','verifier','reverificationTriggers','reverificationStatus','feedbackCorrections','productDecision','accessibilityDecision','dataQualityDecision','contentDecision','operationsDecision','disposition','releasePackage'] as const;
export function validatePlatformGuidanceRegistry(raw: readonly unknown[]): readonly PlatformGuidanceRecord[] {
  const ids = new Set<string>(); return deepFreeze(raw.map((value) => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Platform guidance record must be an object'); const root = value as Record<string,unknown>; for (const field of FIELDS) if (!(field in root) || root[field] === '' || root[field] == null) throw new Error(`38-field platform guidance coverage row missing ${field}`); const record = root as unknown as PlatformGuidanceRecord; if (ids.has(record.coverageRowId)) throw new Error('Duplicate platform guidance coverage row identity'); ids.add(record.coverageRowId); return record; }));
}
export function resolvePlatformGuidance(raw: readonly unknown[], request: PlatformGuidanceRequest): PlatformGuidanceRecord | undefined {
  if (request.rerouted || request.platformState !== 'confirmed' || !request.orientation) return undefined;
  return validatePlatformGuidanceRegistry(raw).find((record) => {
    const reviews=[record.productDecision,record.accessibilityDecision,record.dataQualityDecision,record.contentDecision,record.operationsDecision];
    const release = record.releasePackage;
    const releaseDecisionAllowed = request.exposure.surface === 'validation' || release.downstreamDecision === 'approved';
    return exposureAllowsEvaluation(request.exposure, release.packageVersion, 'guidance') && release.inclusion==='included' && release.scope==='exact-scope' && releaseDecisionAllowed && Boolean(release.reason) && record.complex===request.complex && record.constituent===request.constituent && record.route===request.route && record.servicePattern===request.servicePattern && record.direction===request.direction && record.destination===request.destination && record.platformId===request.platformId && record.layoutOrientation===request.orientation && record.objectiveType===request.objectiveType && record.objectiveTarget===request.objectiveTarget && record.accessiblePathVersion===request.accessiblePathVersion && Number.isFinite(Date.parse(`${record.verificationDate}T00:00:00Z`)) && record.reverificationStatus.startsWith('current|') && record.disposition.startsWith('eligible-for-runtime-evaluation|') && reviews.every((decision)=>decision.startsWith(`approve|${record.immutableVersion}|`)) && record.provenance?.immutable===true && record.provenance.reviewed===true && record.provenance.version===record.immutableVersion && Boolean(record.provenance.sourceId);
  });
}
function deepFreeze<T>(value:T):T { if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))deepFreeze(child);}return value; }
